# Generated by Django 4.0.5 on 2022-06-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('AgentId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Hired', models.DateField()),
                ('Birthday', models.DateField()),
                ('City', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('ReportId', models.AutoField(primary_key=True, serialize=False)),
                ('Period', models.CharField(max_length=100)),
                ('volume', models.FloatField()),
                ('AgentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.agents')),
            ],
        ),
    ]
